In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import re

filename = "honey_colony_data/BeeColonies-05-12-2016/hcny_all_tables.csv"

def remove_chars(input_):
    '''
    removes unwanted characters from a line read from a file
    input parameters:
        input_: A list containing a line read from a file
    output:
        output_list: A list containing the line with unwanted characters removed
    '''
    output_ = input_.strip('\n').split(',')
    output_list = [re.sub(r'^"|"$', '', i) for i in output_]
    return output_list

def clean_colony_data(file_):
    '''
    Reads in the USDA honey colony data files and outputs 2 cleaned dataframes
    One pertaining to the colony count data per state, and the second dataframe containing
    the colony diseases per state.
    
    input parameters: 
        file_: string containing file path 
        
    returns:
        colony_df: Dataframe containing data of colony counts per state
        disease_df: Dataframe containing the colony disease counts per state
    '''
    #Remove unwanted characters in file lines
    f = [remove_chars(i) for i in open(filename)]
    
    #looking at the excel table we know that colony data has 10 columns
    #disease data has nine columns, and that these rowtypes are classified
    #as data rows with character 'd'. Thus we subset these specific
    #data rows by their lengths.
    
    colony_data = [i for i in f if len(i) == 10 for j in i if j == 'd']
    disease_data = [i for i in f if len(i) == 9 for j in i if j == 'd']
    
    #The data for each quarter starts with Alabama and ends with the United States total
    #By getting these indexes, we can separate all quarters in the file
    colony_start_indexes = [colony_data.index(colony_data[i]) for i in range(len(colony_data)) for j in colony_data[i] if j == 'Alabama']
    disease_start_indexes = [disease_data.index(disease_data[i]) for i in range(len(disease_data)) for j in disease_data[i] if j == 'Alabama']
    
    colony_end_indexes = [colony_data.index(colony_data[i]) for i in range(len(colony_data)) for j in colony_data[i] if j == 'Wyoming']
    disease_end_indexes = [disease_data.index(disease_data[i]) for i in range(len(disease_data)) for j in disease_data[i] if j == 'Wyoming']
    
    #subset the data by with the index values collected
    colony_subsets = [colony_data[colony_start_indexes[i]: colony_end_indexes[i]] for i in range(len(colony_start_indexes))]    
    quarters = ['Q1', 'Q2', 'Q3', 'Q4', 'Q5']
    
    #append the quarter labels
    for i in range(len(colony_subsets)):
        for j in colony_subsets[i]:
            j.append(quarters[i])
    
    cleaned_colony_data = [j for i in colony_subsets for j in i]
    
    #Subset the disease data and append the quarter labels
    disease_subsets = [disease_data[disease_start_indexes[i]: disease_end_indexes[i]] for i in range(len(disease_start_indexes))]    
    for i in range(len(disease_subsets)):
        for j in disease_subsets[i]:
            j.append(quarters[i])
    
    cleaned_disease_data = [j for i in disease_subsets for j in i]
    
    #Convert the cleaned data into dataframes
    colony_df = pd.DataFrame(cleaned_colony_data)
    colony_df.columns = ["table_no", "row_type", "state", "initial_count", "max", "lost", "lost_perc", "added", "renovated", "renovated_perc", "quarter"]
    
    disease_df = pd.DataFrame(cleaned_disease_data)
    disease_df.columns = ["table_no", "row_type", "state", "varroa_mites", "other_pests", "diseases", "pesticides", "other", "unknown", "quarter"]
    
    colony_df.drop(columns=['table_no', 'row_type'], inplace = True)
    disease_df.drop(columns=['table_no', 'row_type'], inplace = True)

    colony_df.replace(['(X)', '-'], "", inplace = True)
    colony_df.replace(['(Z)'], "0", inplace = True)

    disease_df.replace(['(X)', '-'], '', inplace = True)
    disease_df.replace(['(Z)'], '0', inplace = True)


    categoricals = ['state', 'quarter']
    for (columnName, columnData) in colony_df.iteritems():
        if(columnName not in categoricals):
            colony_df[columnName] = pd.to_numeric(colony_df[columnName], errors = 'coerce', downcast = 'float')
        else:
            colony_df[columnName] = colony_df[columnName].astype(str)


    for (columnName, columnData) in disease_df.iteritems():
        if(columnName not in categoricals):
            disease_df[columnName] = pd.to_numeric(disease_df[columnName], errors = 'coerce', downcast = 'float')
        else:
            disease_df[columnName] = disease_df[columnName].astype(str)
    
    return (colony_df, disease_df)

In [ ]:
f = [remove_chars(i) for i in open(filename)]

In [ ]:
row_lengths = [len(i) for i in f]

In [ ]:
res = np.array(row_lengths)

In [ ]:
res

In [ ]:
colony_data = [i for i in f if len(i) == 10 for j in i if j == 'd']

In [ ]:
colony_data

In [ ]:
disease_data = [i for i in f if len(i) == 9 for j in i if j == 'd']

In [ ]:
disease_data

In [ ]:
colony_start_indexes = [colony_data.index(colony_data[i]) for i in range(len(colony_data)) for j in colony_data[i] if j == 'Alabama']
disease_start_indexes = [disease_data.index(disease_data[i]) for i in range(len(disease_data)) for j in disease_data[i] if j == 'Alabama']

In [ ]:
colony_end_indexes = [colony_data.index(colony_data[i]) for i in range(len(colony_data)) for j in colony_data[i] if j == 'United States']
disease_end_indexes = [disease_data.index(disease_data[i]) for i in range(len(disease_data)) for j in disease_data[i] if j == 'United States']

In [ ]:
quarters = ['Q1', 'Q2', 'Q3', 'Q4', 'Q5']

In [ ]:
sample = [colony_data[colony_start_indexes[i]: colony_end_indexes[i]] for i in range(len(colony_start_indexes))]

In [ ]:
len(sample)

In [ ]:
for i in range(len(sample)):
    for j in sample[i]:
        j.append(quarters[i])

In [ ]:
sample

In [ ]:
 wow = [j for i in sample for j in i]

In [ ]:
colony_df = pd.DataFrame(wow)
colony_df.columns = ["table_no", "row_type", "state", "initial_count", "max", "lost", "lost_perc", "added", "renovated", "renovated_perc", "quarter"]

In [ ]:
colony_df.head()

In [ ]:
colony_end_indexes

In [5]:
results = clean_colony_data(filename)

In [6]:
results[0].head

,state,initial_count,max,lost,lost_perc,added,renovated,renovated_perc,quarter
0,Alabama,7000.0,7000.0,1800.0,26.0,2800.0,250.0,4.0,Q1
1,Arizona,35000.0,35000.0,4600.0,13.0,3400.0,2100.0,6.0,Q1
2,Arkansas,13000.0,14000.0,1500.0,11.0,1200.0,90.0,1.0,Q1
3,California,1440000.0,1690000.0,255000.0,15.0,250000.0,124000.0,7.0,Q1
4,Colorado,3500.0,12500.0,1500.0,12.0,200.0,140.0,1.0,Q1
5,Connecticut,3900.0,3900.0,870.0,22.0,290.0,NaN,NaN,Q1
6,Florida,305000.0,315000.0,42000.0,13.0,54000.0,25000.0,8.0,Q1
7,Georgia,104000.0,105000.0,14500.0,14.0,47000.0,9500.0,9.0,Q1
8,Hawaii,10500.0,10500.0,380.0,4.0,3400.0,760.0,7.0,Q1
9,Idaho,81000.0,88000.0,3700.0,4.0,2600.0,8000.0,9.0,Q1
10,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q1
11,Illinois,6000.0,10500.0,4200.0,40.0,2300.0,390.0,4.0,Q1
12,Indiana,9000.0,9500.0,2100.0,22.0,490.0,120.0,1.0,Q1
13,Iowa,12500.0,17500.0,3100.0,18.0,1700.0,270.0,2.0,Q1
14,Kansas,4600.0,7000.0,1600.0,23.0,450.0,70.0,1.0,Q1
15,Kentucky,7500.0,10500.0,4100.0,39.0,250.0,NaN,NaN,Q1
16,Louisiana,51000.0,51000.0,8000.0,16.0,3100.0,6500.0,13.0,Q1
17,Maine,3100.0,6500.0,380.0,6.0,20.0,NaN,NaN,Q1
18,Maryland,7500.0,10000.0,4100.0,41.0,1600.0,870.0,9.0,Q1
19,Massachusetts,2900.0,4600.0,1000.0,22.0,260.0,120.0,3.0,Q1
20,Michigan,16500.0,60000.0,11500.0,19.0,7500.0,2400.0,4.0,Q1
21,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q1
22,Minnesota,28000.0,74000.0,3700.0,5.0,690.0,530.0,1.0,Q1
23,Mississippi,34000.0,76000.0,8500.0,11.0,22000.0,7500.0,10.0,Q1
24,Missouri,12000.0,13000.0,2000.0,15.0,220.0,910.0,7.0,Q1
25,Montana,8500.0,36000.0,2200.0,6.0,1400.0,1100.0,3.0,Q1
26,Nebraska,10000.0,31000.0,2600.0,8.0,120.0,310.0,1.0,Q1
27,New Jersey,6000.0,9000.0,1100.0,12.0,570.0,1600.0,18.0,Q1
28,New Mexico,7000.0,7000.0,690.0,10.0,190.0,600.0,9.0,Q1
29,New York,27000.0,30000.0,6500.0,22.0,430.0,950.0,3.0,Q1
...,...,...,...,...,...,...,...,...,...
210,Maryland,6500.0,6500.0,1400.0,22.0,40.0,20.0,0.0,Q5
211,Massachusetts,3000.0,3000.0,370.0,12.0,120.0,330.0,11.0,Q5
212,Michigan,25000.0,37000.0,5000.0,14.0,2300.0,110.0,0.0,Q5
213,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q5
214,Minnesota,37000.0,39000.0,6000.0,15.0,4400.0,10.0,0.0,Q5
215,Mississippi,24000.0,77000.0,6500.0,8.0,11000.0,1700.0,2.0,Q5
216,Missouri,11500.0,11500.0,1200.0,10.0,930.0,290.0,3.0,Q5
217,Montana,15500.0,48000.0,840.0,2.0,11500.0,NaN,NaN,Q5
218,Nebraska,10500.0,21000.0,330.0,2.0,40.0,30.0,0.0,Q5
219,New Jersey,8500.0,8500.0,1000.0,12.0,80.0,40.0,1.0,Q5
220,New Mexico,6000.0,6500.0,1700.0,26.0,10.0,70.0,1.0,Q5
221,New York,31000.0,31000.0,4000.0,13.0,140.0,1400.0,5.0,Q5
222,North Carolina,18500.0,24000.0,2500.0,10.0,80.0,840.0,4.0,Q5
223,North Dakota,82000.0,173000.0,17000.0,10.0,NaN,NaN,NaN,Q5
224,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q5
225,Ohio,16000.0,16000.0,4200.0,26.0,760.0,100.0,1.0,Q5
226,Oklahoma,6000.0,6000.0,2900.0,48.0,60.0,510.0,9.0,Q5
227,Oregon,70000.0,92000.0,2800.0,3.0,3800.0,1800.0,2.0,Q5
228,Pennsylvania,12500.0,12500.0,2900.0,23.0,220.0,340.0,3.0,Q5
229,South Carolina,16500.0,16500.0,3400.0,21.0,2100.0,1800.0,11.0,Q5
230,South Dakota,30000.0,91000.0,770.0,1.0,30.0,NaN,NaN,Q5
231,Tennessee,9000.0,9000.0,1700.0,19.0,100.0,150.0,2.0,Q5
232,Texas,240000.0,290000.0,29000.0,10.0,73000.0,42000.0,15.0,Q5
233,Utah,12000.0,12500.0,1700.0,14.0,710.0,100.0,1.0,Q5
234,Vermont,5500.0,5500.0,410.0,8.0,NaN,NaN,NaN,Q5
235,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q5
236,Virginia,6500.0,6500.0,1100.0,17.0,500.0,130.0,2.0,Q5
237,Washington,78000.0,135000.0,13000.0,10.0,4200.0,2000.0,2.0,Q5
238,West Virginia,6500.0,7500.0,1700.0,23.0,NaN,10.0,0.0,Q5
239,Wisconsin,22000.0,23000.0,2900.0,13.0,530.0,NaN,NaN,Q5